name: flutter_app_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Connect API
  unique_identifier: ^0.2.2
  provider: ^6.0.3
  mime: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  android_intent_plus: ^3.1.1+1

  #image
  cached_network_image: ^3.2.2

  #responsive layout
  flutter_screenutil: ^5.5.4

  #Firebase
  firebase_auth: ^4.1.0
  stacked_firebase_auth: ^0.2.17
  firebase_core: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lang/
    - assets/fonts/
